export const ENV = {
    API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL|| "$NEXT_PUBLIC_API_BASE_URL",
    AUTHORIZATION_TOKEN: process.env.NEXT_PUBLIC_AUTHORIZATION_TOKEN || "$NEXT_PUBLIC_AUTHORIZATION_TOKEN",
  };